version: '2.0'
services:
  api:
    container_name: nest_api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
    environment:
      - DB_HOST=database
  database:
    image: postgres:13
    container_name: nest_db
    ports:
      - ${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
